# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Srijit Mukherjee
description: Srijit Mukherjee's personal website.
baseurl: ""
url: "https://mukherjeesrijit.github.io"
og_image: /assets/img/profile-pic.jpg
google_analytics: "G-GT7M9B1WK5"

header:
  pages:
    # - name: Kali
    #   slug: /kali/
    - name: Home
      slug: /
    - name: CV
      slug: /assets/MyCV_MukherjeeSrijit.pdf
    - name: Publications
    - name: Teaching

collections:
  kali:
    output: true
    permalink: /kali/:name/

footer:
  show_powered_by: false
  contact:
    - type: email
      name: szm6596@psu.edu
      value: mailto:szm6596@psu.edu
  follow:
    - type: googlescholar
      name: Google Scholar
      link: https://scholar.google.com/citations?user=bmQgd0MAAAAJ&hl=en
    - type: linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/srijit-mukherjee/
    - type: github
      name: GitHub
      link: http://github.com/mukherjeesrijit
    - type: youtube
      name: YouTube
      link: https://www.youtube.com/@mukherjeesrijit 
    
# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
